language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev

  # set up conda
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge python=2.7 numpy scipy jupyter bokeh cython matplotlib
  - source activate test-environment
  - conda install -c pkgw-forge python=2.7 pwkit casa-tools casa-python casa-data
  - python -m pip install pip -U
  - python -m pip install setuptools -U
  - pip install codecov coverage
  - python setup.py install
before_script:
  - git config --global user.email "caseyjlaw@gmail.com"
  - git config --global user.name "Travis-CI"
script: 
  - py.test
after_success:
  - coverage run --source rfpipe -m py.test
  - coverage xml
  - codecov
