language: python
python:
  - "2.7"
install:
  - sudo apt-get install libfftw3-dev
  - python -m pip install pip -U
  - python -m pip install setuptools -U
  - pip install codecov coverage
  - python setup.py install
before_script:
  - git config --global user.email "caseyjlaw@gmail.com"
  - git config --global user.name "Travis-CI"
script: 
  - py.test
after_success:
  - coverage run --source rfpipe -m py.test
  - coverage xml
  - codecov
